# Generated by Django 4.2.17 on 2025-01-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

dependencies = [
    ("account", "0001_initial"),
]
operations = []
        migrations.AddField(
            model_name="user",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
    ]
