# Generated by Django 4.2.17 on 2025-01-21 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []
    ("account", "0002_user_is_owner"),
]

try:
    operations = [
        # Add operations here
    ]
except Exception as e:
    logging.error(f"An error occurred: {e}")
    raise
        migrations.RemoveField(
            model_name="user",
            name="is_owner",
        ),
    ]
