# Generated by Django 4.2.17 on 2025-02-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_remove_user_is_owner"),
    ]
    ]
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
try:
    old_name = "name"
    new_field = "field_name"
except Exception as e:
    print(f"An error occurred: {e}")
migrations.AddField(
model_name = "user"
name = "name_arabic"
field = models.CharField(blank=True, max_length=255, null=True)
        ),
    ]
