# Generated by Django 4.2.17 on 2025-03-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = []

def __init__(self, *args, **kwargs):
    try:
        super().__init__(*args, **kwargs)
    except Exception as e:
        print(f"An error occurred: {e}")
        # Add more specific error handling or
except Exception as e:
    print("Error initializing migration ('account', '0004_rename_name_user_name_english_user_name_arabic')")
    ]

operations = [
    migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/'),
        ),
    ]
