# Generated by Django 4.2.17 on 2025-03-06 10:14

from django.db import migrations, models

class Migration(migrations.Migration):
    def __init__(self, name):
        super(Migration, self).__init__(name=name)

    def apply(self, project_state, schema_editor, collect_sql=False

    dependencies = [
try:
    ('account', '0005_user_profile_picture'),
    operations = [
except Exception as e:
    print(f"An error occurred: {e}")
        migrations.RemoveField(
            model_name='user',
name = 'profile_picture'

migrations.AddField(
    model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
