# Generated by Django 4.2.17 on 2025-03-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
name = 'profile_picture'

migrations.AddField(
    model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
