# Generated by Django 5.2.4 on 2025-07-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_plan_dashboarduser_dashboarduserotp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='feature_credits',
        ),
        migrations.AddField(
            model_name='plan',
            name='home_redesign',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='image_to_image',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
model_name='plan',
            name='object_removal',
            field=models.IntegerField(default=0, error_messages={'invalid': 'Enter a valid integer.'}),
        ),
        migrations.AddField(
            model_name='plan',
            name='text_to_image',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='home_redesign',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='image_to_image',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='object_removal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='schedule_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='text_to_image',
            field=models.IntegerField(default=0),
        ),
    ]
