# Generated by Django 4.2.17 on 2025-08-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_usersubscription_feature_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='duration_days',
        ),
migrations.AddField(
    model_name='plan',
            name='duration_type',
            field=models.CharField(choices=[('Monthly', 'monthly'), ('Yearly', 'yearly'), ('One Time Plan', 'one time plan')], default='Monthly', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
model_name = 'plan'
name = 'sketch_to_render'
field = models.IntegerField(default=0)
        ),
migrations.AddField(
    model_name='usersubscription',
            name='sketch_to_render',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
