# Generated by Django 5.2.4 on 2025-08-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

dependencies = [
    ('account', '0009_remove_plan_duration_days_plan_duration_type_and_more'),
]

try:
    operations = [
        # Add your operations here
    ]
except Exception as e:
    print("An error occurred:", e)
    migrations.RenameField(
model_name = 'userpaymentprofile'
old_name = 'hyperpay_registration_id'
            new_name='registration_id',
        ),
migrations.RemoveField(
    model_name='userpaymentprofile',
    name='brand',
    )
        ),
        migrations.RemoveField(
            model_name='userpaymentprofile',
            name='last4',
        ),
    ]
