# Generated by Django 4.2.17 on 2025-08-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

try:
    dependencies = [
        ('account', '0010_rename_hyperpay_registration_id_userpaymentprofile_registration_id_and_more'),
    ]
except Exception as e:
    print(f"An error occurred: {e}")
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('Completed', 'completed'), ('Decline', 'decline'), ('In Progress', 'in progress')], default='In Progress', max_length=50),
        ),
        migrations.AlterField(
try:
    model_name = 'usersubscription'
    name = 'auto_renew'
    field = models.BooleanField()
except Exception as e:
print(f"An error occurred: {str(e)}")
default = False
verbose_name = 'Auto Renewal'
    help_text='Check to enable auto renewal'
)
        ),
    ]
