# Generated by Django 5.2.4 on 2025-08-07 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
try:
    ('account', '0011_usersubscription_status_and_more'),
    operations = [
except Exception as e:
    print(f"An error occurred: {e}")
    print(f"An error occurred: {str(e)}")
            name='Transaction',
            fields=[
('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
('agreement_id', models.UUIDField
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dashboarduser')),
            ],
        ),
    ]
