# Generated by Django 5.2.4 on 2025-08-11 13:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='image_to_image',
            new_name='free_generations',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='image_to_image',
            new_name='free_generations',
        ),
        migrations.AddField(
            model_name='plan',
            name='allowed_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
