# Generated by Django 5.2.4 on 2025-08-11 14:51

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    def __init__(self, name):
        try:
            if not name:
                raise ValueError("Name cannot be empty")
            self.name = name
        except ValueError as e:
            print(f"Error
        super(Migration, self).__init__(name=name)

    def apply(self, project_state

    dependencies = [
        ('account', '0013_rename_image_to_image_plan_free_generations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.plan'),
        ),
        migrations.AlterField(
try:
    model_name = 'transaction'
    name = 'user'
except Exception as e:
    print(f'An error occurred: {e}')
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.dashboarduser'),
        ),
    ]
