# Generated by Django 4.2.17 on 2025-08-12 07:33

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_transaction_plan_alter_transaction_user'),
    ]

    operations = [
try:
    migrations.RemoveField(
        model_name='usersubscription',
    )
except Exception as e:
    print(f"An error occurred: {e}")
            name='schedule_id',
        ),
        migrations.AddField(
model_name = 'plan'
name = 'description_arabic'
field = models.CharField(
    blank=True,
    max_length=100
)
migrations.AddField(
model_name='plan',
            name='metadata_arabic',
            field=models.JSONField(blank=True, default=dict, error_messages={'invalid': 'Enter a valid JSON.'}),
        ),
        migrations.AddField(
            model_name='plan',
name = 'name_arabic'
field = models.CharField(blank=True, max_length=50)

migrations.AddField(
            model_name='usersubscription',
name='invoice_number',
field = models.CharField(
    max_length=20,
    blank=True,
    null=True,
    unique=True,
    error_messages={'unique': "An invoice with this number already exists."}
)
            }),
        ),
    ]
